LBHackney-IT/contact-details-api

.circleci/config.yml
ContactDetailsApi/appsettings.json
terraform/development/dynamodb.tf
terraform/development/main.tf
terraform/development/variables.tf
terraform/production/dynamodb.tf
terraform/production/main.tf
terraform/production/variables.tf
terraform/staging/dynamodb.tf
terraform/staging/main.tf
terraform/staging/variables.tf

https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-492 
The following tasks have been completed:

Dynamodb has been set up

---

.circleci/config.yml

Code fails to be deployed to staging env.
Added missing context to CircleCI config that can potentially fix the problem.

Added missing context in the step deploying Lambda in CircleCI config.

---

.circleci/config.yml

Code fails to be deployed to staging env.
Added missing context to CircleCI config that can potentially fix the problem.

Added missing context to CircleCI config

---

ContactDetailsApi/serverless.yml

Code fails to be deployed to staging env.
Switched from using terraform created user to using an inline policy when deploying serverless.

Policy configuration change.

---

ContactDetailsApi.Tests/DynamoDbTests.cs
ContactDetailsApi.Tests/V1/E2ETests/E2EDynamoDbTest.cs
ContactDetailsApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
ContactDetailsApi/V1/Gateways/DynamoDbGateway.cs
ContactDetailsApi/V1/Infrastructure/DynamoDbDateTimeConverter.cs

[https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-547](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-547)
I have made changes to the Gateway Tests so the data is being inserted into the database and then ensuring that the data matches the entity that we created at the beginning

Gateway tests

---

ContactDetailsApi/Startup.cs
ContactDetailsApi/serverless.yml

https://hackney.atlassian.net/browse/MTTL-610
Enabled CORS for Contact API

MTTL-610 Added CORS for contact API

---

ContactDetailsApi/V1/Domain/Enums.cs

https://hackney.atlassian.net/browse/MTTL-639.
Update the SubType enum with the new "landline" value.

Added landline to SubType enum

---

ContactDetailsApi.Tests/V1/Infrastructure/DynamoDbBoolConverterTests.cs
ContactDetailsApi.sln
ContactDetailsApi/V1/Boundary/Response/ContactDetailsResponseObject.cs
ContactDetailsApi/V1/Domain/AddressExtended.cs
ContactDetailsApi/V1/Domain/ContactDetails.cs
ContactDetailsApi/V1/Domain/Enums.cs
ContactDetailsApi/V1/Factories/EntityFactory.cs
ContactDetailsApi/V1/Infrastructure/ContactDetailsEntity.cs
ContactDetailsApi/V1/Infrastructure/DynamoDbBoolConverter.cs
terraform/development/dynamodb.tf
terraform/production/dynamodb.tf
terraform/staging/dynamodb.tf

Update relaese branch with latest from master

Update from master

---

terraform/development/dynamodb.tf
terraform/production/dynamodb.tf
terraform/staging/dynamodb.tf

Dynamodb update added to all terraform environments

Dynamodb update

---

ContactDetailsApi/V1/Domain/Enums.cs

https://hackney.atlassian.net/browse/MTTL-770
* Updated email contact type enum value

Updated email contact type value

---

.circleci/config.yml
ContactDetailsApi.Tests/V1/E2ETests/Stories/CreateContactTests.cs
terraform/development/main.tf
terraform/production/main.tf
terraform/staging/main.tf

https://hackney.atlassian.net/browse/MTTL-888
Add a new SNS topic for contact details

Mttl-888 Add New Topic

---

.circleci/config.yml
ContactDetailsApi/Startup.cs

Master to release - for staging

---

ContactDetailsApi.Tests/V1/Factories/ContactDetailsSnsFactoryTests.cs
ContactDetailsApi/V1/Domain/Sns/DataItem.cs
ContactDetailsApi/V1/Factories/ContactDetailsSnsFactory.cs

https://hackney.atlassian.net/browse/MTTL-1040

Added extra information for event

---

ContactDetailsApi/V1/Domain/Sns/User.cs
ContactDetailsApi/V1/Factories/ContactDetailsSnsFactory.cs

https://hackney.atlassian.net/browse/MTTL-1096

Removed user id from raised events

---

ContactDetailsApi.Tests/V1/E2ETests/Steps/CreateContactSteps.cs
ContactDetailsApi.Tests/V1/Factories/EntityFactoryTest.cs
ContactDetailsApi/V1/Domain/CreatedBy.cs
ContactDetailsApi/V1/Factories/EntityFactory.cs

https://hackney.atlassian.net/browse/MTTL-1106
Removed the Id property from the CreatedBy.

Removed Id from CreatedBy

---

ContactDetailsApi.Tests/V1/Controllers/ContactDetailsControllerTests.cs
ContactDetailsApi/ContactDetailsApi.csproj

https://hackney.atlassian.net/browse/MTTL-1119.

Updated Hackney.Core package version

---

CODEOWNERS
ContactDetailsApi.Tests/V1/Controllers/ContactDetailsControllerTests.cs
ContactDetailsApi.Tests/V1/E2ETests/Steps/CreateContactSteps.cs
ContactDetailsApi.Tests/V1/Factories/EntityFactoryTest.cs
ContactDetailsApi/ContactDetailsApi.csproj
ContactDetailsApi/V1/Domain/CreatedBy.cs
ContactDetailsApi/V1/Domain/Sns/User.cs
ContactDetailsApi/V1/Factories/ContactDetailsSnsFactory.cs
ContactDetailsApi/V1/Factories/EntityFactory.cs

Release logging changes to staging

Release mttl 1101

---

ContactDetailsApi.Tests/V1/Factories/ContactDetailsSnsFactoryTests.cs
ContactDetailsApi/V1/Domain/Sns/DataItem.cs
ContactDetailsApi/V1/Factories/ContactDetailsSnsFactory.cs

Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
Add descriptions of what changes were made to address the problem and provide a solution.
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
Are there any next steps that need to addressed after merging this PR? Add them here.

Changed enum to int

---

ContactDetailsApi.Tests/V1/Boundary/Request/Validation/AddressExtendedValidatorTests.cs
ContactDetailsApi.Tests/V1/Boundary/Request/Validation/ContactInformationValidatorTests.cs
ContactDetailsApi.Tests/V1/Boundary/Request/Validation/SourceServiceAreaValidatorTests.cs
ContactDetailsApi.Tests/V1/E2ETests/Fixtures/ContactDetailsFixture.cs
ContactDetailsApi.Tests/V1/E2ETests/Steps/CreateContactSteps.cs
ContactDetailsApi.Tests/V1/E2ETests/Stories/CreateContactTests.cs
ContactDetailsApi.Tests/V1/Infrastructure/FluentValidationExtensionsTests.cs
ContactDetailsApi.Tests/V1/Infrastructure/UseErrorCodeInterceptorTests.cs
ContactDetailsApi/Startup.cs
ContactDetailsApi/V1/Boundary/Request/Validation/AddressExtendedValidator.cs
ContactDetailsApi/V1/Boundary/Request/Validation/ContactInformationValidator.cs
ContactDetailsApi/V1/Boundary/Request/Validation/ErrorCodes.cs
ContactDetailsApi/V1/Boundary/Request/Validation/SourceServiceAreaValidator.cs
ContactDetailsApi/V1/Infrastructure/FluentValidationExtensions.cs
ContactDetailsApi/V1/Infrastructure/UseErrorCodeInterceptor.cs

Release MTTL-1067 changes to staging / production

Release mttl 1067

---

terraform/development/dynamodb.tf
terraform/development/main.tf
terraform/development/variables.tf
terraform/production/dynamodb.tf
terraform/production/main.tf
terraform/production/variables.tf
terraform/staging/dynamodb.tf
terraform/staging/main.tf
terraform/staging/variables.tf

https://hackney.atlassian.net/browse/MTTL-1461
Get metrics in easy to view dashboard
Added CW dashboard
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
Are there any next steps that need to addressed after merging this PR? Add them here.

added CW dashboard

---

CODEOWNERS
terraform/development/dynamodb.tf
terraform/development/main.tf
terraform/development/variables.tf
terraform/production/dynamodb.tf
terraform/production/main.tf
terraform/production/variables.tf
terraform/staging/dynamodb.tf
terraform/staging/main.tf
terraform/staging/variables.tf

https://hackney.atlassian.net/browse/MTTL-1461
Get metrics in easy to view dashboard
Added CW dashboard
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
Are there any next steps that need to addressed after merging this PR? Add them here.

Deploy to staging

---

ContactDetailsApi/Startup.cs
ContactDetailsApi/serverless.yml

[Jira Ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-1654)
updating API to ensure that when an x-correlation-id is sent in the request

add correlation header

---

ContactDetailsApi.Tests/AwsIntegrationTests.cs
ContactDetailsApi.Tests/AwsMockWebApplicationFactory.cs
ContactDetailsApi.Tests/ContactDetailsApi.Tests.csproj
ContactDetailsApi.Tests/SnsEventVerifier.cs
ContactDetailsApi.Tests/V1/E2ETests/Steps/CreateContactSteps.cs
ContactDetailsApi.Tests/V1/E2ETests/Steps/DeleteContactDetailsSteps.cs
ContactDetailsApi.Tests/V1/E2ETests/Stories/CreateContactTests.cs
ContactDetailsApi.Tests/V1/E2ETests/Stories/DeleteContactDetailsByTargetIdTests.cs
ContactDetailsApi.Tests/V1/Factories/ContactDetailsSnsFactoryTests.cs
ContactDetailsApi.sln
ContactDetailsApi/V1/Factories/ContactDetailsSnsFactory.cs
ContactDetailsApi/V1/Infrastructure/EventConstants.cs
ContactDetailsApi/V1/UseCase/CreateContactUseCase.cs
ContactDetailsApi/V1/UseCase/DeleteContactDetailsByTargetIdUseCase.cs
docker-compose.yml

https://hackney.atlassian.net/browse/MTTL-1668
Verify that the correct Sns event message gets raised for the corresponding API call.

Implemented SNS event verification in E2E tests

---

.circleci/config.yml
.dockerignore
ContactDetailsApi.Tests/Dockerfile
ContactDetailsApi.Tests/V1/E2ETests/Steps/CreateContactSteps.cs
ContactDetailsApi.Tests/V1/E2ETests/Steps/DeleteContactDetailsSteps.cs
ContactDetailsApi.Tests/V2/E2ETests/Steps/CreateContactSteps.cs
docker-compose.yml
sonar-project.properties

https://hackney.atlassian.net/browse/MTTL-2193
Sonar cloud Pipeline

sonar cloud pipeline

---

.circleci/config.yml
terraform/development/terraform-compliance/dynamodb.feature
terraform/development/terraform-compliance/sns.feature
terraform/production/terraform-compliance/dynamodb.feature
terraform/production/terraform-compliance/sns.feature
terraform/staging/terraform-compliance/dynamodb.feature
terraform/staging/terraform-compliance/sns.feature

[Jira Ticket](https://hackney.atlassian.net/browse/MTTL-2288)
Added TF Compliance rules

Terraform compliance rules

---

.circleci/config.yml

https://hackney.atlassian.net/browse/MTTL-2368
Removed --account-flag from config.yml.
There is no pot:account section on serverless.yml

Removed --account-flag

---

.circleci/config.yml
ContactDetailsApi.sln
ContactDetailsApi/serverless.yml

[JIRA ticket](https://hackney.atlassian.net/browse/MTTL-2401)
Enabled AWS WAF

Enabled AWS WAF

---

.circleci/config.yml
ContactDetailsApi/policies/require-authorizer.js
ContactDetailsApi/serverless.yml

[JIRA ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-2413)

Enable serverless safeguards

---

.circleci/config.yml
ContactDetailsApi.Tests/ContactDetailsApi.Tests.csproj
ContactDetailsApi.Tests/MockWebApplicationFactory.cs
ContactDetailsApi.Tests/V1/E2ETests/Stories/CreateContactTests.cs
ContactDetailsApi.Tests/V1/E2ETests/Stories/DeleteContactDetailsByTargetIdTests.cs
ContactDetailsApi.Tests/V2/E2ETests/Stories/CreateContactTests.cs
docker-compose.yml

https://hackney.atlassian.net/browse/MTTL-2869
Upgrade Hackney.Core.Testing.Sns version to fix bug where tests are falsely passing.

Mttl 2869 - Upgrade Hackney.Core.Testing.Sns version

---

.circleci/config.yml
ContactDetailsApi.Tests/Dockerfile

https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?assignee=624c20c6a629c30068a81020&selectedIssue=MTTL-2956
Resolve SonarCloud Issues

SonarCloud Issue

---

.circleci/config.yml
ContactDetailsApi.Tests/ContactDetailsApi.Tests.csproj
ContactDetailsApi.Tests/Dockerfile
ContactDetailsApi/ContactDetailsApi.csproj
ContactDetailsApi/Dockerfile
ContactDetailsApi/Startup.cs
ContactDetailsApi/build.cmd
ContactDetailsApi/build.sh
ContactDetailsApi/serverless.yml
README.md

https://hackney.atlassian.net/browse/MTTL-3275
Update API to .NET 6 as .NET 3.1 is deprecated.

Update API to .NET 6.0

---

terraform/production/main.tf

Following PR #107 
- Created new branch `angelo/staging-release` based on up-to-date `release` branch
- Merged up-to-date `master` branch into `angelo/staging-release`
- Resolved conflict (main.tf) file
- Merging now into `release`

Staging release

---

ContactDetailsApi.Tests/V1/E2ETests/Fixtures/ContactDetailsFixture.cs
ContactDetailsApi.Tests/V1/E2ETests/Steps/CreateContactSteps.cs
ContactDetailsApi.Tests/V1/E2ETests/Steps/DeleteContactDetailsSteps.cs
ContactDetailsApi.Tests/V1/Factories/EntityFactoryTest.cs
ContactDetailsApi.Tests/V1/Gateways/ContactDetailsDynamoDbGatewayTests.cs
ContactDetailsApi.Tests/V2/Controller/ContactDetailsControllerTests.cs
ContactDetailsApi.Tests/V2/E2ETests/Fixtures/ContactDetailsFixture.cs
ContactDetailsApi.Tests/V2/E2ETests/Steps/CreateContactSteps.cs
ContactDetailsApi.Tests/V2/E2ETests/Steps/PatchContactSteps.cs
ContactDetailsApi.Tests/V2/E2ETests/Stories/PatchContactTests.cs
ContactDetailsApi.Tests/V2/Gateway/ContactDetailsDynamoDbGatewayTests.cs
ContactDetailsApi.Tests/V2/UseCase/EditContactUseCaseTests.cs
ContactDetailsApi/Startup.cs
ContactDetailsApi/V1/Boundary/Response/ContactDetailsResponseObject.cs
ContactDetailsApi/V1/Domain/ContactDetails.cs
ContactDetailsApi/V1/Factories/EntityFactory.cs
ContactDetailsApi/V1/Factories/ResponseFactory.cs
ContactDetailsApi/V1/Gateways/ContactDetailsDynamoDbGateway.cs
ContactDetailsApi/V1/Infrastructure/ContactDetailsEntity.cs
ContactDetailsApi/V2/Controllers/ContactDetailsController.cs
ContactDetailsApi/V2/Domain/ContactDetails.cs
ContactDetailsApi/V2/Factories/EntityFactory.cs
ContactDetailsApi/V2/Gateways/ContactDetailsDynamoDbGateway.cs
ContactDetailsApi/V2/Gateways/Interfaces/IContactDetailsGateway.cs
ContactDetailsApi/V2/Infrastructure/ContactDetailsEntity.cs
ContactDetailsApi/V2/Infrastructure/HeaderConstants.cs
ContactDetailsApi/V2/Infrastructure/VersionNumberConflictException.cs
ContactDetailsApi/V2/UseCase/EditContactDetailsUseCase.cs
ContactDetailsApi/V2/UseCase/Interfaces/IEditContactDetailsUseCase.cs
ContactDetailsApi/serverless.yml

[https://hackney.atlassian.net/browse/MR-761?atlOrigin=eyJpIjoiZWM0ZGQxNGI5NGZlNGQ1YmFlNWIzZWQ1NmVmNjNlNDUiLCJwIjoiaiJ9](https://hackney.atlassian.net/browse/MR-761?atlOrigin=eyJpIjoiZWM0ZGQxNGI5NGZlNGQ1YmFlNWIzZWQ1NmVmNjNlNDUiLCJwIjoiaiJ9)
Add optimistic locking to contact details API.

Add Optimistic Locking to ContactDetailsAPI

---

ContactDetailsApi.Tests/V2/Gateway/ContactDetailsDynamoDbGatewayTests.cs
ContactDetailsApi.Tests/V2/UseCase/FetchAllContactDetailsUseCaseTests.cs
ContactDetailsApi/V2/Gateways/ContactDetailsDynamoDbGateway.cs
ContactDetailsApi/V2/Gateways/Interfaces/IContactDetailsGateway.cs
ContactDetailsApi/V2/UseCase/FetchAllContactDetailsByUprnUseCase.cs

Made a few refactoring changes as the API was failing due to the lambda running out of memory when trying to fetch all the contact details

Refactor get all cds

---

.circleci/config.yml
ContactDetailsApi/V2/Gateways/ContactDetailsDynamoDbGateway.cs

The external Service soft endpoint was failing on staging as there is a record with no contacts in the staging database. I have allowed the list object to be nullable so it can return an empty list of contact details with all the other data given.

Fix staging

---

ContactDetailsApi/V2/UseCase/FetchAllContactDetailsByUprnUseCase.cs

change to firstOrDefaiult() so it doesn't fail if null

pr comment

---

ContactDetailsApi.Tests/V2/Controller/ServiceSoftControllerTests.cs
ContactDetailsApi.Tests/V2/E2ETests/Steps/FetchAllContactDetailsByUprnStep.cs
ContactDetailsApi.Tests/V2/Factories/EntityFactoryTests.cs
ContactDetailsApi.Tests/V2/Factories/ResponseFactoryTests.cs
ContactDetailsApi.Tests/V2/UseCase/FetchAllContactDetailsUseCaseTests.cs
ContactDetailsApi/V2/Boundary/Response/ContactsByUprnList.cs
ContactDetailsApi/V2/Controllers/ServicesoftController.cs
ContactDetailsApi/V2/Domain/ContactUprns.cs
ContactDetailsApi/V2/Factories/EntityFactory.cs
ContactDetailsApi/V2/Factories/ResponseFactory.cs
ContactDetailsApi/V2/UseCase/FetchAllContactDetailsByUprnUseCase.cs
ContactDetailsApi/V2/UseCase/Interfaces/IFetchAllContactDetailsByUprnUseCase.cs

https://hackney.atlassian.net/browse/HPT-5
Tweaks to the servicesoft endpoint.
- Add `/contactDetails` to the endpoint URL for clarity
- Add person id and contact detail ID to payload (to support editing contact details)

ServiceSoft Tweaks

---

ContactDetailsApi.Tests/V2/Controller/ServiceSoftControllerTests.cs
ContactDetailsApi.Tests/V2/E2ETests/Steps/FetchAllContactDetailsByUprnStep.cs
ContactDetailsApi.Tests/V2/Factories/EntityFactoryTests.cs
ContactDetailsApi.Tests/V2/Factories/ResponseFactoryTests.cs
ContactDetailsApi.Tests/V2/UseCase/FetchAllContactDetailsUseCaseTests.cs
ContactDetailsApi/V2/Boundary/Response/ContactsByUprnList.cs
ContactDetailsApi/V2/Controllers/ServicesoftController.cs
ContactDetailsApi/V2/Domain/ContactUprns.cs
ContactDetailsApi/V2/Factories/EntityFactory.cs
ContactDetailsApi/V2/Factories/ResponseFactory.cs
ContactDetailsApi/V2/Gateways/ContactDetailsDynamoDbGateway.cs
ContactDetailsApi/V2/UseCase/FetchAllContactDetailsByUprnUseCase.cs
ContactDetailsApi/V2/UseCase/Interfaces/IFetchAllContactDetailsByUprnUseCase.cs

Deploy ServiceSoft Tweaks

---

ContactDetailsApi/ContactDetailsApi.csproj

Fixing an error with the contact details API due to dependency misalignment

Update xray packages

---

ContactDetailsApi/V2/Gateways/TenureDbGateway.cs

See PR https://github.com/LBHackney-IT/contact-details-api/pull/163

Release disable scan consistent reads

---

.circleci/config.yml
ContactDetailsApi.Tests/ContactDetailsApi.Tests.csproj
ContactDetailsApi.Tests/Dockerfile
ContactDetailsApi.Tests/V1/Controllers/BaseControllerTests.cs
ContactDetailsApi/ContactDetailsApi.csproj
ContactDetailsApi/Dockerfile
ContactDetailsApi/build.cmd
ContactDetailsApi/build.sh
ContactDetailsApi/serverless.yml

Upgrade .et8

---

ContactDetailsApi/serverless.yml

Updated production authorizer ARN

Update production authorizer ARN
